title: Heteroscedastic Gaussian process 
summary: |
  In this example, demonstrates the heteroscedastic Gaussian process model
author:
- family: Yi
  given: Sang-ri
collection-title: Basic example
difficulty: 0
