summary: In this example, a parameter estimation routine is used to estimate column
  stiffnesses of a simple steel frame, given data about its mode shapes and mass
  distribution.

collection-title: 2-Story Frame

difficulty: 0
