abstract: This example uses quoFEM to perform a global sensitivity analysis of an
  OpenSees FE model.
archive: $SIMCENTER_DEV
archive_location: quoFEM/examples/qfem-0004
collection-title: Simple Truss
id: qfem-0004
programming-language: Tcl
title: Sensitivity Analysis
type: book
