abstract: In this example, a **parameter estimation** routine is used to solve a classical
  optimization problem for which an analytic solution is known.
archive: $SIMCENTER_DEV
archive_location: quoFEM/examples/qfem-0006
collection-title: Rosenbrock
id: qfem-0006
programming-language: Python
title: Optimization
type: book
