summary: In this example, Bayesian estimation is used to estimate column stiffnesses
  of a simple steel frame, given data about it's mode shapes and mass distribution.

collection-title: 2-Story Frame


difficulty: 0
